# download data from googlesheet

library(googlesheets)
library(readxl)

# register worksheet
# eDNA_sheet <- gs_title("GBIF eDNA record format")
eDNA_sheet <- gs_title("GBIF eDNA record format - modified")

# Download entire Google Sheet as xlsx
# - to get round "Too Many Requests (RFC 6585) (HTTP 429)" error
#   generated by individual downloads from google.
dataFile <- "./data/eDNA_Data.xlsx"
gs_download(eDNA_sheet, NULL, dataFile, TRUE, TRUE)


# List all sheets (tabs) in the spreadsheet 
excel_sheets(dataFile)


# save individual sheets as dataframes
locality <- read_excel(dataFile, sheet = "locality")
waterSample <- read_excel(dataFile, sheet = "waterSample")
extraction <- read_excel(dataFile, sheet = "extraction")
amplification <- read_excel(dataFile, sheet = "amplification")
sequencing <- read_excel(dataFile, sheet = "sequencing")
occurrence <- read_excel(dataFile, sheet = "occurrence")
sequence <- read_excel(dataFile, sheet = "sequence_AVS")


# save files to local cache
dir.create("./data",showWarnings=FALSE)
saveRDS(locality,"./data/locality.rds")
saveRDS(waterSample,"./data/waterSample.rds")
saveRDS(extraction,"./data/extraction.rds")
saveRDS(amplification,"./data/amplification.rds")
saveRDS(sequencing,"./data/sequencing.rds")
saveRDS(occurrence,"./data/occurrence.rds")
saveRDS(sequence,"./data/sequence.rds")


